### ISSUE TITLE
[CONTRIBUTOR] disable cache by configuration

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-web-contributors#224]
> As the maintainer of ARLAS,
> I want to disable (or reduce) the cache mechanism (or timeout) of a contributor
> So that when I tag hits, I get the powerbars updated soon afterwards

Note: A contributor makes calls to the ARLAS API with a cache-control: max-age=120. This needs to be either disabled or reduced/augmented.

**Comment by mbarbet** [comment]
Cache is currently  the same for all the contributor, we must remove the notion of global cache in the collaborativeSearchService and put a cache in each contributor

**Comment by sylvaingaudan** [comment]
> Cache is currently the same for all the contributor, we must remove the notion of global cache in the collaborativeSearchService and put a cache in each contributor

We can keep the global cache definition and if a specific definition is provided, it takes over the global definition.
