### ISSUE TITLE
MAP: Normalize count between 0 and 1 instead of 0 and 100

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-web-contributors#246]
- [x] Normalize count between 0 and 1 instead of 0 and 100
Ref #251

**Comment by mbarbet** [comment]
> For instance, if speed is one of the returned fields, I want to have a speed_normalized field which values are between 0 and 100
@sylvaingaudan  0 and 100 or 0 and 1 ?

**Comment by sylvaingaudan** [comment]
> > @sylvaingaudan  0 and 100 or 0 and 1 ?

Mathematically, it is much more interesting to have it within the range `[0-1]`. Also, normalising is traditionally projecting the values within that range. However, it seems that the normalised count has been unfortunately projected to `[0-100]`. 

Nevertheless, I still believe that we should keep `[0-1]` with the normalised count being a kind of _anomaly_.

**Comment by sylvaingaudan** [comment]
_Note: Date must also be taken into account._
